### ISSUE TITLE
Add Sticker Art to MCW Site

### ISSUE THREAD

**Issue by BrittJ-MSFT** [Microsoft/MCW#11]
We need to capture all our MCW stickers to be used in various ways in a subdirectory within the MCW site.  These then can be used by anyone to create stickers for various purposes.  As we come up with new stickers we can add them here.

**Comment by BrittJ-MSFT** [comment]
Assigned to @bendq

**Comment by bendq** [comment]
Added all files I could get originals off to https://github.com/Microsoft/MCW/upload/master/Stickers 

Additional a bunch of additional Go, GitHub and other interesting stickers from our dev advocates team

We can share with field who can add more images as they find them and also use them on sticker mule as required
