### ISSUE TITLE
Hands-On-Lab Not found

### ISSUE THREAD

**Issue by cheahengsoon** [Microsoft/MCW#12]
Some of the Hands-On-Lab Not found in the Learning Download Center.
For example: Azure Security And Management

**Comment by waltermyersiii** [comment]
Learning Download Center?

**Comment by cheahengsoon** [comment]
@waltermyersiii https://learningdownloadcenter.microsoft.com

**Comment by waltermyersiii** [comment]
@cheahengsoon, this content is unrelated to the Learning Download Center.

**Comment by waltermyersiii** [comment]
Harder to keep up to date. It's GitHub or bust.
