### ISSUE TITLE
HOL Content

### ISSUE THREAD

**Issue by milazzom** [Microsoft/MCW#16]
I saw closed issue #12 related to HOL content missing.  I do not have access to the learning download site, and as a CSA, I need to be able to get this content.  How can I resolve this?  I believe the content should reside here in GitHub with the relevant workshop.

Thanks!

Mike

**Comment by waltermyersiii** [comment]
We don't have any of our content on the learning download site, so not sure what is the problem.

**Comment by ciphertxt** [comment]
The HOL content for each MCW does reside in the MCW specific repo. For example, the HOL for Enterprise Ready Cloud can be found at https://github.com/Microsoft/MCW-Enterprise-ready-cloud/tree/master/Hands-on%20lab and Resilient IaaS Architecture at https://github.com/Microsoft/MCW-Building-a-resilient-IaaS-architecture/tree/master/Hands-on%20lab.

The repository structure is always MCW-Name/Hands-on lab/. 

Some labs do have external dependencies such as ARM templates, but all of those are publicly accessible in their respective repos as well and cleary linked in the labs themselves.

**Comment by milazzom** [comment]
The problem is that artifacts in the HOL are missing, not just in one
workshop, but multiple.

Specifically, DSC scripts from the lift/shift with ARM workshop. The final
templates folder has boilerplate scripts, but don’t achieve the desired
result.

**Comment by DawnmarieDesJardins** [comment]
Michael, have you looked at the Before the HOL documents in the workshops you're viewing?  The before the lab documents have set up guides and I think you'll find what you're looking for there.

**Comment by waltermyersiii** [comment]
Michael, this should be in the context of a particular HOL. We did have a fix the other week with a wrong pointer to content. Please close this and open for a specific workshop. We don't have an artifacts missing but possibly a bad link.

**Comment by milazzom** [comment]
I figured it out.  The student files are NOT part of the workshop, but are instead posted to blob storage.  I found the file I needed for this workshop.  Thanks!
