### ISSUE TITLE
Formatting of Slide #9 in Deck 01B

### ISSUE THREAD

**Issue by davel501** [microsoft/MCW#27]
The formatting of slides 9 and 10 seem to hide the sample only tag under the actual text making it easy to miss.

**Comment by hopero929** [comment]
Hi @davel501, it is hard for me to respond without seeing what you are referring to. All of the updated "how to" content is here now: https://microsoftcloudworkshop.com/HowToDeliver/. Please review this and let me know if there is anything that needs to be clarified. Thank you.

**Comment by davel501** [comment]
It looks like I was in the wrong place. This seems to be a template for the workshop I was supposed to be reviewing but I ended up down in here. I was just saying that in deck 01B slides 9 and 10 had a graphic that was masked.
