### ISSUE TITLE
Incorrect content description on homepage

### ISSUE THREAD

**Issue by thommck** [microsoft/MCW#31]
On your homepage, microsoftcloudworkshop.com, one of the workshops, **Hybrid Identity**, has the incorrect description.
![image](https://user-images.githubusercontent.com/29751878/81544562-9b0a0700-936f-11ea-977f-2c6e14ea358b.png)

The link goes to the correct page around hybrid identity but the description is all around networking.

**Comment by DawnmarieDesJardins** [comment]
@thommck @paulopsgility
Thanks Thom!  I've brought this to the attention of our authors.  They are working on a June update for Hybrid identity and will review the abstracts and we'll adjust the MCW page.

**Comment by DawnmarieDesJardins** [comment]
Description updated, closing issue.
